#pragma once

enum enumEnemy {
	SLIME,
	GOLEM,
	MIKU,
	FIRE_SLIME,
	ICE_SLIME
};

enum enumSkillHolder {
	FIREBALL_SKILLHOLDER,
	SNOWBALL_SKILLHOLDER,
	WINDSTORM_SKILLHOLDER
};

enum enumModal {
	SETTING_MODAL,
	SHOP_MODAL
};

enum enumButtonInGame {
	SETTING_BUTTON,
	SHOP_BUTTON,
	MENU_BUTTON,
	RESUME_BUTTON,
};

enum enumButtonInGamoverScene {
	MENU_BUTTON_GAMEOVER,
	RESTART_BUTTON_GAMEOVER
};

enum enumTextInGame {
	SETTING_TEXT,
	MENU_TEXT,
	RESUME_TEXT,
	PLAY_TEXT,
	QUIT_TEXT,
	SETTING_MODAL_TEXT,
	SHOP_TEXT,
	COIN_TEXT,
	LEVELUP_FIREBALL_TEXT,
	LEVELUP_SNOWBALL_TEXT,
	LEVELUP_WINDSTORM_TEXT,
	GAMEHP_TEXT,
	GAMEOVER_TEXT
};

enum enumSFX {
	BUTTON_SFX,
	FIREBALL_SFX,
	SNOWBALL_SFX,
	WINDSTORM_SFX,
	LEVELUP_SFX
};

enum enumMusic {
	GAMEPLAY_MUSIC,
	GAMEOVER_MUSIC,
	MENU_MUSIC
};

enum enumAnimation {
	PLAYER_IDLE_ANIMATION,
	SLIME_ANIMATION,
	GRASS_ANIMATION,
	FIREBALL_ANIMATION,
	BUTTON_NORMAL_ANIMATION,
	BUTTON_HOVER_ANIMATION,
	BUTTON_ACTIVE_ANIMATION,
	MODAL_ANIMATION,
	BACKGROUND_ANIMATION,
	SNOWBALL_ANIMATION,
	WINDSTORM_ANIMATION,
	FIREBALL_SKILLHOLDER_ANIMATION,
	SNOWBALL_SKILLHOLDER_ANIMATION,
	WINDSTORM_SKILLHOLDER_ANIMATION,
	FIREBALL_SKILLHOLDER_COOLDOWN_ANIMATION,
	SNOWBALL_SKILLHOLDER_COOLDOWN_ANIMATION,
	WINDSTORM_SKILLHOLDER_COOLDOWN_ANIMATION,
	OUTERBAR_ANIMATION,
	INNER_HP_BAR_ANIMATION,
	INNER_COOLDOWN_BAR_ANIMATION,
	LONGBUTTON_NORMAL_ANIMATION,
	LONGBUTTON_HOVER_ANIMATION,
	LONGBUTTON_ACTIVE_ANIMATION,
	INDICATOR_ANIMATION,
	GOLEM_MOVE_ANIMATION,
	MIKU_MOVE_ANIMATION,
	FIRESLIME_ANIMATION,
	ICESLIME_ANIMATION,
	MENU_BACKGROUND_ANIMATION
};